name: docker release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get the tag name
        id: get_tag
        run: echo ::set-output name=TAG::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/certbot_dns_porkbun:latest
            ${{ secrets.DOCKER_USERNAME }}/certbot_dns_porkbun:${{ steps.get_tag.outputs.TAG }}
            ghcr.io/${{ secrets.GH_USERNAME }}/certbot_dns_porkbun:latest
            ghcr.io/${{ secrets.GH_USERNAME }}/certbot_dns_porkbun:${{ steps.get_tag.outputs.TAG }}
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
